version: "3.8"

services:
  db:
    image: fabiodcorreia/mariadb:latest
    container_name: mariadb_codimd
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - DATABASE_ROOT=321.qwerty
      - DATABASE_NAME=codimddb
      - DATABASE_USER=codimduser
      - DATABASE_PASS=codimdpass
    ports:
      - 3306:3306

  codimd:
    image: fabiodcorreia/codimd:latest
    container_name: codimd
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
      - DATABASE_HOST=mariadb_codimd
      - DATABASE_PORT=3306
      - DATABASE_NAME=codimddb
      - DATABASE_USER=codimduser
      - DATABASE_PASS=codimdpass
      - DOMAIN_NAME=localhost
      - ADD_PORT_URL=true
    volumes:
      - app_config:/config
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  app_config: {}
  db_data: {}
